sudo: required
dist: trusty
language: generic
install: git clone https://github.com/QubesOS/qubes-builder ~/qubes-builder
script: ~/qubes-builder/scripts/travis-build
# keep the log under 4MB limit
env:
 - DIST_DOM0=fc25 USE_QUBES_REPO_VERSION=4.0 VERBOSE=0
 - DISTS_VM=fc24 USE_QUBES_REPO_VERSION=4.0 VERBOSE=0
 - DISTS_VM=fc25 USE_QUBES_REPO_VERSION=4.0 VERBOSE=0
 - DISTS_VM=jessie USE_QUBES_REPO_VERSION=4.0
 - DISTS_VM=stretch USE_QUBES_REPO_VERSION=4.0
